import styles from './landing-hero.module.scss';

const Key = () => {
  return (
    <svg
      viewBox="0 0 532 564"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={`${styles['hero-img']} ${styles['hero-key']}`}
    >
      <mask
        id="mask1_1899_178144"
        // style="mask-type:luminance"
        style={{ maskType: 'alpha' }}
        maskUnits="userSpaceOnUse"
        x="69"
        y="78"
        width="394"
        height="420"
      >
        <path
          d="M437.609 130.817C433.804 117.5 423.341 107.036 410.023 103.231L325.837 79.45C312.044 75.645 296.824 79.45 286.836 89.4381L227.383 149.367C217.395 159.355 213.114 174.575 216.919 188.368L240.701 272.554V273.029L74.7075 439.498C67.0975 447.108 67.0975 458.999 74.7075 466.609C78.5125 470.414 83.2687 472.316 88.025 472.316C92.7812 472.316 97.5375 470.414 101.342 466.609L117.989 449.962L160.32 492.292C164.125 496.097 168.881 498 173.637 498C178.394 498 183.15 496.097 186.955 492.292C194.565 484.682 194.565 472.792 186.955 465.182L144.624 422.851L157.942 409.534L183.626 435.217C187.431 439.022 192.187 440.925 196.943 440.925C201.699 440.925 206.456 439.022 210.261 435.217C217.871 427.607 217.871 415.717 210.261 408.107L184.577 382.423L267.811 300.14H268.287L352.472 323.921C366.266 327.726 381.486 323.921 391.474 313.933L450.927 254.48C460.915 244.492 465.196 229.272 461.391 215.479L437.609 130.817ZM362.461 219.759L329.642 211.198L321.081 178.856L344.862 155.074L377.205 163.636L385.766 195.978L362.461 219.759Z"
          fill="white"
        />
      </mask>

      <g mask="url(#mask1_1899_178144)">
        <rect
          x="292"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="460"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="460"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="460"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="82"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="68"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="82"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="68"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="82"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="475"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="475"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="475"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="489"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="489"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
      </g>
    </svg>
  );
};

export default Key;
