import styles from './landing-hero.module.scss';

const Key = () => {
  return (
    <svg
      viewBox="0 0 532 564"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={`${styles['hero-img']}`}
    >
      <g>
        <rect
          x="292"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="83"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="97"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="111"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="125"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="139"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="153"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="167"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="181"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="195"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="460"
          y="209"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="460"
          y="223"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="460"
          y="237"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="446"
          y="251"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="432"
          y="265"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="418"
          y="279"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="264"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="278"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="404"
          y="293"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="250"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="292"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="306"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="320"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="334"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="390"
          y="307"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="236"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="348"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="362"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="376"
          y="321"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="222"
          y="335"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="349"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="363"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="377"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="391"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="405"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="419"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="82"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="194"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="208"
          y="433"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="68"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="82"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="110"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="124"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="447"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="68"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="82"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="96"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="138"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="461"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="152"
          y="475"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="475"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="475"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="166"
          y="489"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
        <rect
          x="180"
          y="489"
          width="4"
          height="4"
          rx="2"
          fill="currentColor"
          data-shape="key"
        />
      </g>
    </svg>
  );
};

export default Key;
