import EncryptionImg from './assets/encryption.png';
import ServerlessImg from './assets/serverless.png';
import WalletImg from './assets/wallet.png';
import styles from './landing-products.module.scss';

const LandingProducts = () => {
  return (
    <section className={styles.container}>
      <div className={styles.header}>
        <div className={styles.badge}>
          <span>Powerful Tooling</span>
        </div>
        <h2 className={styles.title}>Sign, encrypt, and compute</h2>
        <p className={styles.subtitle}>
          No centralized authority can prevent or control access to the keys
          generated by the Lit network. Use Lit to build experiences with
          greater privacy, flexibility, and control.
        </p>
      </div>
      <div className={styles.product}>
        <img
          src={WalletImg}
          alt="Auth providers leading to a wallet"
          className={`${styles.product__img} ${styles['product__img--wallet']}`}
        />
        <div className={styles.product__description}>
          <div>
            <h3 className={styles.product__title}>
              Streamline user experience with{' '}
              <span className={styles.product__highlight}>
                programmable wallets
              </span>
            </h3>
            <p className={styles.product__copy}>
              Empower your users with portable and scalable wallets secured by
              intuitive authentication like social logins and passkeys. Deliver
              seamless onboarding, easy recovery, and user-centric security
              features&#8212;all without worrying about private key management.
            </p>
          </div>
          <a
            href="https://developer.litprotocol.com/v2/concepts/pkpsAsWallet"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.product__link}
          >
            Learn more &#8594;
          </a>
        </div>
      </div>
      <div className={styles.product}>
        <img
          src={EncryptionImg}
          alt="Conditional encryption"
          className={`${styles.product__img} ${styles['product__img--encryption']}`}
        />
        <div className={styles.product__description}>
          <div>
            <h3 className={styles.product__title}>
              Protect sensitive data with{' '}
              <span className={styles.product__highlight}>
                flexible access control
              </span>
            </h3>
            <p className={styles.product__copy}>
              Define conditional rules to control access to confidential data,
              stored anywhere. Lit will validate your rules and grant decryption
              capabilities, without ever accessing the private data.
            </p>
          </div>
          <a
            href="https://developer.litprotocol.com/v2/accessControl/intro"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.product__link}
          >
            Learn more &#8594;
          </a>
        </div>
      </div>
      <div className={styles.product}>
        <img
          src={ServerlessImg}
          alt="Clouds above code"
          className={`${styles.product__img} ${styles['product__img--serverless']}`}
        />
        <div className={styles.product__description}>
          <div>
            <h3 className={styles.product__title}>
              Supercharge your apps with{' '}
              <span className={styles.product__highlight}>
                serverless automations
              </span>
            </h3>
            <p className={styles.product__copy}>
              Write serverless function logic to drive event-based signing,
              encryption, and identity management. Ship and iterate faster
              without the burden of scaling key infrastructure.
            </p>
          </div>
          <a
            href="https://developer.litprotocol.com/v2/LitActions/intro"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.product__link}
          >
            Learn more &#8594;
          </a>
        </div>
      </div>
    </section>
  );
};

export default LandingProducts;
